query ($where: service_realtime_service_bool_exp, $limit: Int, $offset: Int) {
  services: service_realtime_service(
    where: $where
    limit: $limit
    offset: $offset
  ) {
    id
    title
    logo
    availability
    license

    supplier {
      userById {
        email
        first_name
      }
    }
    reviewer {
      first_name
    }
    logo
    description
    release_status
    images: realtime_service_media {
      url
    }
    created_at
    category: realtime_service_category {
      id
      language: original_language {
        translation_contents(where: { language_type: { _eq: "en" } }) {
          name
        }
      }
    }
  }
  total: service_realtime_service_aggregate(where: $where) {
    service: aggregate {
      value: count
    }
  }
}
