query {
  category: service_realtime_service_category {
    id
    logo
    language: original_language {
      id
      en: translation_contents(where: { language_type: { _eq: "en" } }) {
        name
        id: original_content_id
      }
      am: translation_contents(where: { language_type: { _eq: "am" } }) {
        name
        id: original_content_id
      }
    }
  }
}
