
interface _GlobalComponents {
      'CategoryForm': typeof import("../components/category-form.vue")['default']
    'CategoryMenu': typeof import("../components/category-menu.vue")['default']
    'ConfirmAction': typeof import("../components/confirm_action.vue")['default']
    'HButton': typeof import("../components/h/button.vue")['default']
    'HDialog': typeof import("../components/h/dialog.vue")['default']
    'HDragAndDrop': typeof import("../components/h/drag-and-drop.vue")['default']
    'HEmpty': typeof import("../components/h/empty.vue")['default']
    'HFileUpload': typeof import("../components/h/file-upload.vue")['default']
    'HLoading': typeof import("../components/h/loading.vue")['default']
    'HNotification': typeof import("../components/h/notification.vue")['default']
    'HSelect': typeof import("../components/h/select.vue")['default']
    'HTextArea': typeof import("../components/h/text-area.vue")['default']
    'HTextField': typeof import("../components/h/text-field.vue")['default']
    'LocationAddForm': typeof import("../components/location-add-form.vue")['default']
    'LocationEditAddForm': typeof import("../components/location-edit-add-form.vue")['default']
    'RtpCategoryForm': typeof import("../components/rtp-category-form.vue")['default']
    'VSwiper': typeof import("../components/v-swiper.vue")['default']
    'VLoading': typeof import("../components/v/loading.vue")['default']
    'VMenu': typeof import("../components/v/menu.vue")['default']
    'VNotification': typeof import("../components/v/notification.vue")['default']
    'VPagination': typeof import("../components/v/pagination.vue")['default']
    'VSearch': typeof import("../components/v/search.vue")['default']
    'VSelect': typeof import("../components/v/select.vue")['default']
    'VTable': typeof import("../components/v/table.vue")['default']
    'VTextArea': typeof import("../components/v/text-area.vue")['default']
    'VTextField': typeof import("../components/v/text-field.vue")['default']
    'VeProductTable': typeof import("../components/ve-product-table.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture")['default']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyCategoryForm': typeof import("../components/category-form.vue")['default']
    'LazyCategoryMenu': typeof import("../components/category-menu.vue")['default']
    'LazyConfirmAction': typeof import("../components/confirm_action.vue")['default']
    'LazyHButton': typeof import("../components/h/button.vue")['default']
    'LazyHDialog': typeof import("../components/h/dialog.vue")['default']
    'LazyHDragAndDrop': typeof import("../components/h/drag-and-drop.vue")['default']
    'LazyHEmpty': typeof import("../components/h/empty.vue")['default']
    'LazyHFileUpload': typeof import("../components/h/file-upload.vue")['default']
    'LazyHLoading': typeof import("../components/h/loading.vue")['default']
    'LazyHNotification': typeof import("../components/h/notification.vue")['default']
    'LazyHSelect': typeof import("../components/h/select.vue")['default']
    'LazyHTextArea': typeof import("../components/h/text-area.vue")['default']
    'LazyHTextField': typeof import("../components/h/text-field.vue")['default']
    'LazyLocationAddForm': typeof import("../components/location-add-form.vue")['default']
    'LazyLocationEditAddForm': typeof import("../components/location-edit-add-form.vue")['default']
    'LazyRtpCategoryForm': typeof import("../components/rtp-category-form.vue")['default']
    'LazyVSwiper': typeof import("../components/v-swiper.vue")['default']
    'LazyVLoading': typeof import("../components/v/loading.vue")['default']
    'LazyVMenu': typeof import("../components/v/menu.vue")['default']
    'LazyVNotification': typeof import("../components/v/notification.vue")['default']
    'LazyVPagination': typeof import("../components/v/pagination.vue")['default']
    'LazyVSearch': typeof import("../components/v/search.vue")['default']
    'LazyVSelect': typeof import("../components/v/select.vue")['default']
    'LazyVTable': typeof import("../components/v/table.vue")['default']
    'LazyVTextArea': typeof import("../components/v/text-area.vue")['default']
    'LazyVTextField': typeof import("../components/v/text-field.vue")['default']
    'LazyVeProductTable': typeof import("../components/ve-product-table.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture")['default']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CategoryForm: typeof import("../components/category-form.vue")['default']
export const CategoryMenu: typeof import("../components/category-menu.vue")['default']
export const ConfirmAction: typeof import("../components/confirm_action.vue")['default']
export const HButton: typeof import("../components/h/button.vue")['default']
export const HDialog: typeof import("../components/h/dialog.vue")['default']
export const HDragAndDrop: typeof import("../components/h/drag-and-drop.vue")['default']
export const HEmpty: typeof import("../components/h/empty.vue")['default']
export const HFileUpload: typeof import("../components/h/file-upload.vue")['default']
export const HLoading: typeof import("../components/h/loading.vue")['default']
export const HNotification: typeof import("../components/h/notification.vue")['default']
export const HSelect: typeof import("../components/h/select.vue")['default']
export const HTextArea: typeof import("../components/h/text-area.vue")['default']
export const HTextField: typeof import("../components/h/text-field.vue")['default']
export const LocationAddForm: typeof import("../components/location-add-form.vue")['default']
export const LocationEditAddForm: typeof import("../components/location-edit-add-form.vue")['default']
export const RtpCategoryForm: typeof import("../components/rtp-category-form.vue")['default']
export const VSwiper: typeof import("../components/v-swiper.vue")['default']
export const VLoading: typeof import("../components/v/loading.vue")['default']
export const VMenu: typeof import("../components/v/menu.vue")['default']
export const VNotification: typeof import("../components/v/notification.vue")['default']
export const VPagination: typeof import("../components/v/pagination.vue")['default']
export const VSearch: typeof import("../components/v/search.vue")['default']
export const VSelect: typeof import("../components/v/select.vue")['default']
export const VTable: typeof import("../components/v/table.vue")['default']
export const VTextArea: typeof import("../components/v/text-area.vue")['default']
export const VTextField: typeof import("../components/v/text-field.vue")['default']
export const VeProductTable: typeof import("../components/ve-product-table.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture")['default']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyCategoryForm: typeof import("../components/category-form.vue")['default']
export const LazyCategoryMenu: typeof import("../components/category-menu.vue")['default']
export const LazyConfirmAction: typeof import("../components/confirm_action.vue")['default']
export const LazyHButton: typeof import("../components/h/button.vue")['default']
export const LazyHDialog: typeof import("../components/h/dialog.vue")['default']
export const LazyHDragAndDrop: typeof import("../components/h/drag-and-drop.vue")['default']
export const LazyHEmpty: typeof import("../components/h/empty.vue")['default']
export const LazyHFileUpload: typeof import("../components/h/file-upload.vue")['default']
export const LazyHLoading: typeof import("../components/h/loading.vue")['default']
export const LazyHNotification: typeof import("../components/h/notification.vue")['default']
export const LazyHSelect: typeof import("../components/h/select.vue")['default']
export const LazyHTextArea: typeof import("../components/h/text-area.vue")['default']
export const LazyHTextField: typeof import("../components/h/text-field.vue")['default']
export const LazyLocationAddForm: typeof import("../components/location-add-form.vue")['default']
export const LazyLocationEditAddForm: typeof import("../components/location-edit-add-form.vue")['default']
export const LazyRtpCategoryForm: typeof import("../components/rtp-category-form.vue")['default']
export const LazyVSwiper: typeof import("../components/v-swiper.vue")['default']
export const LazyVLoading: typeof import("../components/v/loading.vue")['default']
export const LazyVMenu: typeof import("../components/v/menu.vue")['default']
export const LazyVNotification: typeof import("../components/v/notification.vue")['default']
export const LazyVPagination: typeof import("../components/v/pagination.vue")['default']
export const LazyVSearch: typeof import("../components/v/search.vue")['default']
export const LazyVSelect: typeof import("../components/v/select.vue")['default']
export const LazyVTable: typeof import("../components/v/table.vue")['default']
export const LazyVTextArea: typeof import("../components/v/text-area.vue")['default']
export const LazyVTextField: typeof import("../components/v/text-field.vue")['default']
export const LazyVeProductTable: typeof import("../components/ve-product-table.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image-edge/dist/runtime/components/nuxt-picture")['default']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
